import styles from "../styles/404.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Nav from "../components/navigation";

const FourOhFour: NextPage = () => {
    return (
    <>
        <Head>
            <title>404</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <main className={styles.main}>
            <div className={styles.container}>
                <img src="/404.png" className={styles.img} />
                <h2 className={styles.subtitle}>
                    Page not found.
                </h2>
            </div>
        </main>
    </>
    );
};

export default FourOhFour;
